-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE `greshni_logove` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(255),
	`pass` varchar(255),
	`data` varchar(15),
	`ip` varchar(15),
	`browser` varchar(1023),
	`komentar` text,
	`otsite` varchar(15),
	CONSTRAINT `greshni_logove_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `item` (
	`item_id` int AUTO_INCREMENT NOT NULL,
	`porach_id` int NOT NULL DEFAULT 0,
	`cat_id` varchar(30),
	`item_br` int NOT NULL DEFAULT 0,
	`item_dat` varchar(15),
	`it_cena` float NOT NULL DEFAULT 0,
	`it_suma` float NOT NULL DEFAULT 0,
	`koment` text,
	`komentadm` text,
	`item_br_new` int,
	`it_suma_new` float,
	`ot_adm` int NOT NULL DEFAULT 1,
	`no_nal` int NOT NULL DEFAULT 1,
	`grup_otstup` int NOT NULL DEFAULT 0,
	`prioritet_micro` varchar(20),
	`promot` varchar(20),
	`it_cena_new` float,
	`promot_new` varchar(20),
	`cat_no` varchar(255),
	`ime` varchar(511),
	`miarka` varchar(31),
	`ime_lat` varchar(255),
	`potr_id` varchar(31),
	`potr_ime` varchar(511),
	`q0011_sklad` int NOT NULL DEFAULT 0,
	`q03_bucuresti` int NOT NULL DEFAULT 0,
	`q12_burgas` int NOT NULL DEFAULT 0,
	`q14_burgascentar` int NOT NULL DEFAULT 0,
	`q15_burgashobby` int NOT NULL DEFAULT 0,
	`q22_sofia` int NOT NULL DEFAULT 0,
	`q23_sofiandk` int NOT NULL DEFAULT 0,
	`q24_szagora` int NOT NULL DEFAULT 0,
	`q26_varna` int NOT NULL DEFAULT 0,
	`q28_ruse` int NOT NULL DEFAULT 0,
	`q31_vtarnovo` int NOT NULL DEFAULT 0,
	`q32_shumen` int NOT NULL DEFAULT 0,
	`q34_yambol` int NOT NULL DEFAULT 0,
	`q36_haskovo` int NOT NULL DEFAULT 0,
	`q38_goriahovica` int NOT NULL DEFAULT 0,
	`q41_sliven` int NOT NULL DEFAULT 0,
	`q43_plovdiv` int NOT NULL DEFAULT 0,
	`q51_burgaskiki` int NOT NULL DEFAULT 0,
	`q100_slujeben` int NOT NULL DEFAULT 0,
	`prom` int NOT NULL DEFAULT 1,
	`zelen` int NOT NULL DEFAULT 1,
	`ip` varchar(15),
	`nalichnost` int NOT NULL DEFAULT 0,
	`gramaj` int NOT NULL DEFAULT 0,
	`total` int NOT NULL DEFAULT 0,
	`obem_dalzhina` float NOT NULL DEFAULT 0,
	`obem_visochina` float NOT NULL DEFAULT 0,
	`obem_shirina` float NOT NULL DEFAULT 0,
	`obem_total` float NOT NULL DEFAULT 0,
	CONSTRAINT `item_item_id` PRIMARY KEY(`item_id`)
);
--> statement-breakpoint
CREATE TABLE `itemiztrit` (
	`item_id` int AUTO_INCREMENT NOT NULL,
	`porach_id` int NOT NULL DEFAULT 0,
	`cat_id` varchar(30),
	`item_br` int NOT NULL DEFAULT 0,
	`item_dat` varchar(15),
	`it_cena` float NOT NULL DEFAULT 0,
	`it_suma` float NOT NULL DEFAULT 0,
	`koment` text,
	`komentadm` text,
	`item_br_new` int,
	`it_suma_new` float,
	`ot_adm` int NOT NULL DEFAULT 1,
	`no_nal` int NOT NULL DEFAULT 1,
	`grup_otstup` int NOT NULL DEFAULT 0,
	`prioritet_micro` varchar(20),
	`promot` varchar(20),
	`it_cena_new` float,
	`promot_new` varchar(20),
	`cat_no` varchar(255),
	`ime` varchar(511),
	`miarka` varchar(31),
	`ime_lat` varchar(255),
	`potr_id` varchar(31),
	`potr_ime` varchar(511),
	`q0011_sklad` int NOT NULL DEFAULT 0,
	`q03_bucuresti` int NOT NULL DEFAULT 0,
	`q12_burgas` int NOT NULL DEFAULT 0,
	`q14_burgascentar` int NOT NULL DEFAULT 0,
	`q15_burgashobby` int NOT NULL DEFAULT 0,
	`q22_sofia` int NOT NULL DEFAULT 0,
	`q23_sofiandk` int NOT NULL DEFAULT 0,
	`q24_szagora` int NOT NULL DEFAULT 0,
	`q26_varna` int NOT NULL DEFAULT 0,
	`q28_ruse` int NOT NULL DEFAULT 0,
	`q31_vtarnovo` int NOT NULL DEFAULT 0,
	`q32_shumen` int NOT NULL DEFAULT 0,
	`q34_yambol` int NOT NULL DEFAULT 0,
	`q36_haskovo` int NOT NULL DEFAULT 0,
	`q38_goriahovica` int NOT NULL DEFAULT 0,
	`q41_sliven` int NOT NULL DEFAULT 0,
	`q43_plovdiv` int NOT NULL DEFAULT 0,
	`q51_burgaskiki` int NOT NULL DEFAULT 0,
	`q100_slujeben` int NOT NULL DEFAULT 0,
	`prom` int NOT NULL DEFAULT 1,
	`zelen` int NOT NULL DEFAULT 1,
	`ip` varchar(15),
	CONSTRAINT `itemiztrit_item_id` PRIMARY KEY(`item_id`)
);
--> statement-breakpoint
CREATE TABLE `klienti` (
	`klienti_id` int AUTO_INCREMENT NOT NULL,
	`email_reg` varchar(127),
	`parola` varchar(127),
	`email` varchar(127),
	`ime_familia` varchar(255),
	`ime_familia_adr` varchar(255),
	`darjava` varchar(127),
	`region` varchar(127),
	`oblast` varchar(127),
	`obshtina` varchar(127),
	`grad_selo` varchar(127),
	`post_kod` varchar(31),
	`adres` varchar(511),
	`telefon` varchar(63),
	`br_dop_adresi` int NOT NULL DEFAULT 0,
	`data_reg` varchar(63),
	`data_promiana` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	`f_firma` varchar(255),
	`f_eik` varchar(63),
	`f_dds` varchar(63),
	`f_darjava` varchar(127),
	`f_oblast` varchar(127),
	`f_obshtina` varchar(127),
	`f_grad_selo` varchar(127),
	`f_post_kod` varchar(31),
	`f_adres` varchar(511),
	`f_telefon` varchar(63),
	`f_mol` varchar(255),
	`f_poluchatel` varchar(255),
	`br_dop_firmi` int NOT NULL DEFAULT 0,
	`otstapka` int NOT NULL DEFAULT 0,
	`otstapka2` int NOT NULL DEFAULT 0,
	`otstapka3` int NOT NULL DEFAULT 0,
	`grupa_otstapki` int NOT NULL DEFAULT 0,
	`zakluchen` int NOT NULL DEFAULT 1,
	`status` int NOT NULL DEFAULT 1,
	`email_otpisani` int NOT NULL DEFAULT 1,
	`email_otpisani_data` varchar(63),
	`email_greshen` int NOT NULL DEFAULT 1,
	`reklama` int NOT NULL DEFAULT 1,
	`grupa` varchar(127),
	`kategorizacia` varchar(127),
	`tip` varchar(127),
	`komentar` text,
	`zabelejki` text,
	`microkod` varchar(63),
	`microddsbanka` int NOT NULL DEFAULT 0,
	`broi_porachki` int NOT NULL DEFAULT 0,
	`suma` float NOT NULL DEFAULT 0,
	`pordata_last` varchar(63),
	`porizp_last_status` varchar(127),
	`telefon2` varchar(63),
	`email2` varchar(511),
	`www` varchar(255),
	`ip` varchar(31),
	`zapomni_me` int NOT NULL DEFAULT 1,
	`izbran_adres` int NOT NULL DEFAULT 0,
	`izbrana_firma` int NOT NULL DEFAULT 0,
	`id_svarzani_klienti` varchar(127),
	`ivo_dubl_no` varchar(63),
	`ivo_dubl` varchar(63),
	`ivo_dubl2` varchar(127),
	`dubl_micro` varchar(127),
	`ivo_sort1` varchar(127),
	`ivo_sort2` varchar(127),
	`ivo_sort3` varchar(127),
	`ivo_sort4` varchar(127),
	`ivo_coment` varchar(127),
	`ivo_coment2` varchar(127),
	`broi_logvania` int NOT NULL DEFAULT 0,
	`data_posl_logvane` varchar(15),
	`old_grad` varchar(255),
	`old_nik` varchar(63),
	`old_vapros` varchar(127),
	`old_otgovor` varchar(127),
	`old_ime` varchar(127),
	`old_prezime` varchar(127),
	`old_familia` varchar(127),
	`old_pol` varchar(15),
	`old_r_data_d` int NOT NULL DEFAULT 0,
	`old_r_data_m` varchar(31),
	`old_r_data_g` int NOT NULL DEFAULT 0,
	`fid` varchar(31),
	`regot` varchar(1),
	`ime_first` varchar(127),
	`ime_middle` varchar(127),
	`ime_last` varchar(127),
	`otcite` varchar(15),
	`rojdenna_data` varchar(63),
	CONSTRAINT `klienti_klienti_id` PRIMARY KEY(`klienti_id`),
	CONSTRAINT `email_reg` UNIQUE(`email_reg`)
);
--> statement-breakpoint
CREATE TABLE `klienti_dop_adresi` (
	`klienti_dop_adresi_id` int AUTO_INCREMENT NOT NULL,
	`klienti_id` int NOT NULL,
	`ime_familia` varchar(255),
	`darjava` varchar(127),
	`region` varchar(127),
	`oblast` varchar(127),
	`obshtina` varchar(127),
	`grad_selo` varchar(127),
	`post_kod` varchar(31),
	`adres` varchar(511),
	`telefon` varchar(63),
	CONSTRAINT `klienti_dop_adresi_klienti_dop_adresi_id` PRIMARY KEY(`klienti_dop_adresi_id`)
);
--> statement-breakpoint
CREATE TABLE `klienti_dop_firmi` (
	`klienti_dop_firmi_id` int AUTO_INCREMENT NOT NULL,
	`klienti_id` int NOT NULL,
	`f_firma` varchar(255),
	`f_eik` varchar(63),
	`f_dds` varchar(63),
	`f_darjava` varchar(127),
	`f_oblast` varchar(127),
	`f_obshtina` varchar(127),
	`f_grad_selo` varchar(127),
	`f_post_kod` varchar(31),
	`f_adres` varchar(511),
	`f_telefon` varchar(63),
	`f_mol` varchar(255),
	`f_poluchatel` varchar(255),
	CONSTRAINT `klienti_dop_firmi_klienti_dop_firmi_id` PRIMARY KEY(`klienti_dop_firmi_id`)
);
--> statement-breakpoint
CREATE TABLE `klienti_ip` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(255),
	`ip` varchar(15),
	`br` int NOT NULL DEFAULT 0,
	`mango` varchar(63),
	CONSTRAINT `klienti_ip_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `klienti_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`id_klient` int NOT NULL,
	`email` varchar(255),
	`ip_last_log` varchar(15),
	`data_log` varchar(15),
	`fid` varchar(255),
	`komentar1` text,
	`komentar2` text,
	`fb_id` varchar(255),
	`fb_google_registered` int NOT NULL DEFAULT 0,
	`fb_last_data_logged` varchar(15),
	`google_last_data_logged` varchar(15),
	`ime_first` varchar(255),
	`log_ne_log` int NOT NULL DEFAULT 0,
	`ot_kade` varchar(31),
	CONSTRAINT `klienti_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `poliaci` (
	`poliaci_id` int AUTO_INCREMENT NOT NULL,
	`potrebid` int NOT NULL DEFAULT 0,
	`ime` varchar(255),
	`email` varchar(255),
	`poliaciid` varchar(63),
	`message` text,
	`success` int NOT NULL DEFAULT 1,
	`external` varchar(255),
	`datata` varchar(15),
	`ipto` varchar(15),
	`otkade` varchar(15),
	`otskript` varchar(31),
	CONSTRAINT `poliaci_poliaci_id` PRIMARY KEY(`poliaci_id`)
);
--> statement-breakpoint
CREATE TABLE `poliaci1` (
	`poliaci_id` int AUTO_INCREMENT NOT NULL,
	`potrebid` int NOT NULL DEFAULT 0,
	`ime` varchar(255),
	`email` varchar(255),
	`poliaciid` varchar(63),
	`message` text,
	`success` int NOT NULL DEFAULT 1,
	`external` varchar(255),
	`datata` varchar(15),
	`ipto` varchar(15),
	`otkade` varchar(15),
	`otskript` varchar(31),
	CONSTRAINT `poliaci1_poliaci_id` PRIMARY KEY(`poliaci_id`)
);
--> statement-breakpoint
CREATE TABLE `poliaci_old_do_20211216` (
	`poliaci_id` int AUTO_INCREMENT NOT NULL,
	`potrebid` int NOT NULL DEFAULT 0,
	`ime` varchar(255),
	`email` varchar(255),
	`poliaciid` varchar(63),
	`message` text,
	`success` int NOT NULL DEFAULT 1,
	`external` varchar(255),
	`datata` varchar(15),
	`ipto` varchar(15),
	`otkade` varchar(15),
	`otskript` varchar(31),
	CONSTRAINT `poliaci_old_do_20211216_poliaci_id` PRIMARY KEY(`poliaci_id`)
);
--> statement-breakpoint
CREATE TABLE `porachki` (
	`porachki_id` int AUTO_INCREMENT NOT NULL,
	`potreb_id` int NOT NULL DEFAULT 0,
	`porach` int NOT NULL DEFAULT 1,
	`pordata` varchar(31),
	`pordost` int NOT NULL DEFAULT 0,
	`porizp` int NOT NULL DEFAULT 0,
	`porizp_ime` varchar(255) NOT NULL DEFAULT 'Нов',
	`porizpdat` varchar(31),
	`broi_dni` int NOT NULL DEFAULT 0,
	`porgr` int NOT NULL DEFAULT 0,
	`porcomtr` text,
	`porcomadm` text,
	`porcor` varchar(255),
	`shtane` varchar(255),
	`tovaritelnica` varchar(127),
	`kod_micro` varchar(51),
	`izpaln_id` int NOT NULL DEFAULT 0,
	`izpaln_ime` varchar(255),
	`info_my` int NOT NULL DEFAULT 1,
	`do_kade` int NOT NULL DEFAULT 1,
	`faktura` int NOT NULL DEFAULT 1,
	`izbran_adr` int NOT NULL DEFAULT 0,
	`izpaln1_id` int NOT NULL DEFAULT 0,
	`izpaln1_ime` varchar(255),
	`magaz_id` int NOT NULL DEFAULT 0,
	`magaz_ime` varchar(255),
	`magaz1_id` int NOT NULL DEFAULT 0,
	`magaz1_ime` varchar(255),
	`poluchsumi` int NOT NULL DEFAULT 0,
	`poluchsuma` float NOT NULL DEFAULT 0,
	`poluchsumd` varchar(31),
	`broi_pera` int NOT NULL DEFAULT 0,
	`porach_suma` float NOT NULL DEFAULT 0,
	`email` varchar(127),
	`ime_familia` varchar(255),
	`ime_familia_adr` varchar(255),
	`darjava` varchar(127),
	`region` varchar(127),
	`oblast` varchar(127),
	`obshtina` varchar(127),
	`grad_selo` varchar(127),
	`post_kod` varchar(63),
	`adres` varchar(511),
	`telefon` varchar(63),
	`f_firma` varchar(255),
	`f_eik` varchar(63),
	`f_dds` varchar(63),
	`f_darjava` varchar(127),
	`f_oblast` varchar(127),
	`f_obshtina` varchar(127),
	`f_grad_selo` varchar(127),
	`f_post_kod` varchar(63),
	`f_adres` varchar(511),
	`f_telefon` varchar(63),
	`f_mol` varchar(255),
	`f_poluchatel` varchar(255),
	`izbran_adres` int NOT NULL DEFAULT 0,
	`izbrana_firma` int NOT NULL DEFAULT 0,
	`brkomen` int NOT NULL DEFAULT 0,
	`cendost` float,
	`klmicrokod` varchar(63),
	`ot_site` varchar(31),
	`ip` varchar(15),
	`valuta` varchar(15),
	`kurs` float NOT NULL DEFAULT 0,
	`kurr` float NOT NULL DEFAULT 1,
	`tipdds` int NOT NULL DEFAULT 1,
	`cendost_izchislena` float NOT NULL DEFAULT 0,
	`cendost_emart_plashta` float NOT NULL DEFAULT 0,
	`cendost_kurier_realna` float NOT NULL DEFAULT 0,
	`cendost_kurier_emart` float NOT NULL DEFAULT 0,
	CONSTRAINT `porachki_porachki_id` PRIMARY KEY(`porachki_id`)
);
--> statement-breakpoint
CREATE TABLE `porachki_msg` (
	`porachki_msg_id` int AUTO_INCREMENT NOT NULL,
	`porachki_id` int,
	`msg_text` text,
	`msg_email` int NOT NULL DEFAULT 1,
	`msg_data` varchar(20),
	`msg_kol` int NOT NULL DEFAULT 1,
	CONSTRAINT `porachki_msg_porachki_msg_id` PRIMARY KEY(`porachki_msg_id`)
);
--> statement-breakpoint
CREATE TABLE `porachkimsgiztrit` (
	`porachki_msg_id` int AUTO_INCREMENT NOT NULL,
	`porachki_id` int,
	`msg_text` text,
	`msg_email` int NOT NULL DEFAULT 1,
	`msg_data` varchar(20),
	CONSTRAINT `porachkimsgiztrit_porachki_msg_id` PRIMARY KEY(`porachki_msg_id`)
);
--> statement-breakpoint
CREATE TABLE `porachkiztriti` (
	`porachki_id` int AUTO_INCREMENT NOT NULL,
	`potreb_id` int NOT NULL DEFAULT 0,
	`porach` int NOT NULL DEFAULT 1,
	`pordata` varchar(31),
	`pordost` int NOT NULL DEFAULT 0,
	`porizp` int NOT NULL DEFAULT 0,
	`porizp_ime` varchar(255),
	`porizpdat` varchar(31),
	`broi_dni` int NOT NULL DEFAULT 0,
	`porgr` int NOT NULL DEFAULT 0,
	`porcomtr` text,
	`porcomadm` text,
	`porcor` varchar(63),
	`shtane` varchar(255),
	`tovaritelnica` varchar(127),
	`kod_micro` varchar(51),
	`izpaln_id` int NOT NULL DEFAULT 0,
	`izpaln_ime` varchar(255),
	`info_my` int NOT NULL DEFAULT 1,
	`do_kade` int NOT NULL DEFAULT 1,
	`faktura` int NOT NULL DEFAULT 1,
	`izbran_adr` int NOT NULL DEFAULT 0,
	`izpaln1_id` int NOT NULL DEFAULT 0,
	`izpaln1_ime` varchar(255),
	`magaz_id` int NOT NULL DEFAULT 0,
	`magaz_ime` varchar(255),
	`magaz1_id` int NOT NULL DEFAULT 0,
	`magaz1_ime` varchar(255),
	`poluchsumi` int NOT NULL DEFAULT 0,
	`poluchsuma` float NOT NULL DEFAULT 0,
	`poluchsumd` varchar(31),
	`broi_pera` int NOT NULL DEFAULT 0,
	`porach_suma` float NOT NULL DEFAULT 0,
	`email` varchar(127),
	`ime_familia` varchar(255),
	`ime_familia_adr` varchar(255),
	`darjava` varchar(127),
	`region` varchar(127),
	`oblast` varchar(127),
	`obshtina` varchar(127),
	`grad_selo` varchar(127),
	`post_kod` varchar(63),
	`adres` varchar(511),
	`telefon` varchar(63),
	`f_firma` varchar(255),
	`f_eik` varchar(63),
	`f_dds` varchar(63),
	`f_darjava` varchar(127),
	`f_oblast` varchar(127),
	`f_obshtina` varchar(127),
	`f_grad_selo` varchar(127),
	`f_post_kod` varchar(63),
	`f_adres` varchar(511),
	`f_telefon` varchar(63),
	`f_mol` varchar(255),
	`f_poluchatel` varchar(255),
	`izbran_adres` int NOT NULL DEFAULT 0,
	`izbrana_firma` int NOT NULL DEFAULT 0,
	`brkomen` int NOT NULL DEFAULT 0,
	`cendost` float,
	`klmicrokod` varchar(63),
	`ot_site` varchar(31),
	`ip` varchar(15),
	`valuta` varchar(15),
	`dataiztr` varchar(15),
	`koiiztrid` int NOT NULL DEFAULT 0,
	CONSTRAINT `porachkiztriti_porachki_id` PRIMARY KEY(`porachki_id`)
);
--> statement-breakpoint
CREATE TABLE `promocii_q` (
	`catalog_id` int AUTO_INCREMENT NOT NULL,
	`cat_no` varchar(255),
	`ime` varchar(511),
	`q_total_nalichni` int NOT NULL DEFAULT 0,
	`q_total_porachani` int NOT NULL DEFAULT 0,
	`q_count_porachani` int NOT NULL DEFAULT 0,
	`q_total_nalichni_start` int NOT NULL DEFAULT 1,
	`aktivna_neaktivna` int NOT NULL,
	`data` varchar(64),
	`koment_1` text,
	`koment_2` text,
	`cena` float(5,2) NOT NULL DEFAULT 0,
	`gr_otst` float NOT NULL DEFAULT 0,
	`br_1` int NOT NULL DEFAULT 0,
	`cena_1` float(5,2) NOT NULL DEFAULT 0,
	`br_2` int NOT NULL DEFAULT 0,
	`cena_2` float(5,2) NOT NULL DEFAULT 0,
	`prioritet_micro` varchar(63),
	`tip_stokata` varchar(255),
	`q0011_sklad` int NOT NULL DEFAULT 0,
	`q12_burgas` int NOT NULL DEFAULT 0,
	`q14_burgascentar` int NOT NULL DEFAULT 0,
	`q15_burgashobby` int NOT NULL DEFAULT 0,
	`q22_sofia` int NOT NULL DEFAULT 0,
	`q23_sofiandk` int NOT NULL DEFAULT 0,
	`q24_szagora` int NOT NULL DEFAULT 0,
	`q26_varna` int NOT NULL DEFAULT 0,
	`q28_ruse` int NOT NULL DEFAULT 0,
	`q31_vtarnovo` int NOT NULL DEFAULT 0,
	`q32_shumen` int NOT NULL DEFAULT 0,
	`q34_yambol` int NOT NULL DEFAULT 0,
	`q36_haskovo` int NOT NULL DEFAULT 0,
	`q43_plovdiv` int NOT NULL DEFAULT 0,
	`q_total` int NOT NULL DEFAULT 0,
	`q_count_nalichni_v_magazini` int NOT NULL DEFAULT 0,
	`dost_cena` float(5,2) NOT NULL DEFAULT 0,
	`p_cengr_2` float NOT NULL DEFAULT 0,
	`p_cengr_3` float NOT NULL DEFAULT 0,
	`koment_3` text,
	`koment_4` text,
	`vidimost` int NOT NULL DEFAULT 0,
	`p_acti` int NOT NULL DEFAULT 0,
	`bez_kolichka` int NOT NULL DEFAULT 0,
	`nova_stoka_aktiv` int NOT NULL DEFAULT 0,
	`nalichnost` int NOT NULL DEFAULT 0,
	CONSTRAINT `promocii_q_catalog_id` PRIMARY KEY(`catalog_id`),
	CONSTRAINT `cat_no` UNIQUE(`cat_no`)
);
--> statement-breakpoint
CREATE TABLE `rating` (
	`rating_id` int AUTO_INCREMENT NOT NULL,
	`kod` varchar(255),
	`ocenka` int NOT NULL DEFAULT 5,
	`sesia_id` int NOT NULL DEFAULT 0,
	`klient_id` int NOT NULL DEFAULT 0,
	`otsite` varchar(7) NOT NULL DEFAULT 'bg',
	CONSTRAINT `rating_rating_id` PRIMARY KEY(`rating_id`)
);
--> statement-breakpoint
CREATE TABLE `rating_prazna` (
	`rating_id` int AUTO_INCREMENT NOT NULL,
	`kod` varchar(255),
	`ocenka` int NOT NULL DEFAULT 5,
	`sesia_id` int NOT NULL DEFAULT 0,
	`klient_id` int NOT NULL DEFAULT 0,
	`otsite` varchar(7) NOT NULL DEFAULT '',
	CONSTRAINT `rating_prazna_rating_id` PRIMARY KEY(`rating_id`)
);
--> statement-breakpoint
CREATE TABLE `smizp` (
	`smizp_id` int AUTO_INCREMENT NOT NULL,
	`porid` int NOT NULL DEFAULT 0,
	`magid` int NOT NULL DEFAULT 0,
	`magime` varchar(255),
	`izpid` int NOT NULL DEFAULT 0,
	`izpime` varchar(255),
	`sumid` int NOT NULL DEFAULT 0,
	`sumime` varchar(255),
	`suma` float NOT NULL DEFAULT 0,
	`koga` varchar(15),
	`koiid` int NOT NULL DEFAULT 0,
	`koiime` varchar(255),
	CONSTRAINT `smizp_smizp_id` PRIMARY KEY(`smizp_id`)
);
--> statement-breakpoint
CREATE TABLE `smstat` (
	`smstat_id` int AUTO_INCREMENT NOT NULL,
	`porid` int NOT NULL DEFAULT 0,
	`statid` int NOT NULL DEFAULT 0,
	`statime` varchar(255),
	`koga` varchar(15),
	`koiid` int NOT NULL DEFAULT 0,
	`koiime` varchar(255),
	CONSTRAINT `smstat_smstat_id` PRIMARY KEY(`smstat_id`)
);
--> statement-breakpoint
CREATE TABLE `snimki` (
	`snimki_id` int AUTO_INCREMENT NOT NULL,
	`catno` varchar(255) NOT NULL DEFAULT '',
	`ime` varchar(255) NOT NULL DEFAULT '',
	`direk` varchar(255) NOT NULL DEFAULT '',
	`shirochina` int NOT NULL DEFAULT 0,
	`visochina` int NOT NULL DEFAULT 0,
	`cviat` varchar(128) NOT NULL DEFAULT '',
	`nomer` int NOT NULL DEFAULT 0,
	`tip` int NOT NULL DEFAULT 0,
	CONSTRAINT `snimki_snimki_id` PRIMARY KEY(`snimki_id`)
);
--> statement-breakpoint
CREATE TABLE `tuvar` (
	`tuvar_id` int AUTO_INCREMENT NOT NULL,
	`porid` int NOT NULL DEFAULT 0,
	`tovari` varchar(255),
	`cd1` float NOT NULL DEFAULT 0,
	`cd2` float NOT NULL DEFAULT 0,
	`koga` varchar(15),
	`koiid` int NOT NULL DEFAULT 0,
	`koiime` varchar(255),
	CONSTRAINT `tuvar_tuvar_id` PRIMARY KEY(`tuvar_id`)
);
--> statement-breakpoint
CREATE TABLE `txt_ip` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tip` int NOT NULL DEFAULT 0,
	`ip` varchar(31) NOT NULL,
	`opis` text NOT NULL,
	CONSTRAINT `txt_ip_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE INDEX `porach_id` ON `item` (`porach_id`);--> statement-breakpoint
CREATE INDEX `porachki_id` ON `porachki_msg` (`porachki_id`);--> statement-breakpoint
CREATE INDEX `kod` ON `rating` (`kod`);--> statement-breakpoint
CREATE INDEX `sesia_id` ON `rating` (`sesia_id`);--> statement-breakpoint
CREATE INDEX `kod` ON `rating_prazna` (`kod`);--> statement-breakpoint
CREATE INDEX `sesia_id` ON `rating_prazna` (`sesia_id`);--> statement-breakpoint
CREATE INDEX `izpid` ON `smizp` (`izpid`);--> statement-breakpoint
CREATE INDEX `koga` ON `smizp` (`koga`);--> statement-breakpoint
CREATE INDEX `magid` ON `smizp` (`magid`);--> statement-breakpoint
CREATE INDEX `porid` ON `smizp` (`porid`);--> statement-breakpoint
CREATE INDEX `sumid` ON `smizp` (`sumid`);--> statement-breakpoint
CREATE INDEX `koga` ON `smstat` (`koga`);--> statement-breakpoint
CREATE INDEX `porid` ON `smstat` (`porid`);--> statement-breakpoint
CREATE INDEX `catno` ON `snimki` (`catno`);
*/