import {
  mysqlTable,
  mysqlSchema,
  AnyMySqlColumn,
  primaryKey,
  int,
  varchar,
  text,
  index,
  float,
  unique,
  timestamp,
} from 'drizzle-orm/mysql-core';
import { sql } from 'drizzle-orm';

export const greshniLogove = mysqlTable(
  'greshni_logove',
  {
    id: int().autoincrement().notNull(),
    email: varchar({ length: 255 }),
    pass: varchar({ length: 255 }),
    data: varchar({ length: 15 }),
    ip: varchar({ length: 15 }),
    browser: varchar({ length: 1023 }),
    komentar: text(),
    otsite: varchar({ length: 15 }),
  },
  table => [primaryKey({ columns: [table.id], name: 'greshni_logove_id' })],
);

export const item = mysqlTable(
  'item',
  {
    itemId: int('item_id').autoincrement().notNull(),
    porachId: int('porach_id').default(0).notNull(),
    catId: varchar('cat_id', { length: 30 }),
    itemBr: int('item_br').default(0).notNull(),
    itemDat: varchar('item_dat', { length: 15 }),
    itCena: float('it_cena').notNull(),
    itSuma: float('it_suma').notNull(),
    koment: text(),
    komentadm: text(),
    itemBrNew: int('item_br_new'),
    itSumaNew: float('it_suma_new'),
    otAdm: int('ot_adm').default(1).notNull(),
    noNal: int('no_nal').default(1).notNull(),
    grupOtstup: int('grup_otstup').default(0).notNull(),
    prioritetMicro: varchar('prioritet_micro', { length: 20 }),
    promot: varchar({ length: 20 }),
    itCenaNew: float('it_cena_new'),
    promotNew: varchar('promot_new', { length: 20 }),
    catNo: varchar('cat_no', { length: 255 }),
    ime: varchar({ length: 511 }),
    miarka: varchar({ length: 31 }),
    imeLat: varchar('ime_lat', { length: 255 }),
    potrId: varchar('potr_id', { length: 31 }),
    potrIme: varchar('potr_ime', { length: 511 }),
    q0011Sklad: int('q0011_sklad').default(0).notNull(),
    q03Bucuresti: int('q03_bucuresti').default(0).notNull(),
    q12Burgas: int('q12_burgas').default(0).notNull(),
    q14Burgascentar: int('q14_burgascentar').default(0).notNull(),
    q15Burgashobby: int('q15_burgashobby').default(0).notNull(),
    q22Sofia: int('q22_sofia').default(0).notNull(),
    q23Sofiandk: int('q23_sofiandk').default(0).notNull(),
    q24Szagora: int('q24_szagora').default(0).notNull(),
    q26Varna: int('q26_varna').default(0).notNull(),
    q28Ruse: int('q28_ruse').default(0).notNull(),
    q31Vtarnovo: int('q31_vtarnovo').default(0).notNull(),
    q32Shumen: int('q32_shumen').default(0).notNull(),
    q34Yambol: int('q34_yambol').default(0).notNull(),
    q36Haskovo: int('q36_haskovo').default(0).notNull(),
    q38Goriahovica: int('q38_goriahovica').default(0).notNull(),
    q41Sliven: int('q41_sliven').default(0).notNull(),
    q43Plovdiv: int('q43_plovdiv').default(0).notNull(),
    q51Burgaskiki: int('q51_burgaskiki').default(0).notNull(),
    q100Slujeben: int('q100_slujeben').default(0).notNull(),
    prom: int().default(1).notNull(),
    zelen: int().default(1).notNull(),
    ip: varchar({ length: 15 }),
    nalichnost: int().default(0).notNull(),
    gramaj: int().default(0).notNull(),
    total: int().default(0).notNull(),
    obemDalzhina: float('obem_dalzhina').notNull(),
    obemVisochina: float('obem_visochina').notNull(),
    obemShirina: float('obem_shirina').notNull(),
    obemTotal: float('obem_total').notNull(),
  },
  table => [index('porach_id').on(table.porachId), primaryKey({ columns: [table.itemId], name: 'item_item_id' })],
);

export const itemiztrit = mysqlTable(
  'itemiztrit',
  {
    itemId: int('item_id').autoincrement().notNull(),
    porachId: int('porach_id').default(0).notNull(),
    catId: varchar('cat_id', { length: 30 }),
    itemBr: int('item_br').default(0).notNull(),
    itemDat: varchar('item_dat', { length: 15 }),
    itCena: float('it_cena').notNull(),
    itSuma: float('it_suma').notNull(),
    koment: text(),
    komentadm: text(),
    itemBrNew: int('item_br_new'),
    itSumaNew: float('it_suma_new'),
    otAdm: int('ot_adm').default(1).notNull(),
    noNal: int('no_nal').default(1).notNull(),
    grupOtstup: int('grup_otstup').default(0).notNull(),
    prioritetMicro: varchar('prioritet_micro', { length: 20 }),
    promot: varchar({ length: 20 }),
    itCenaNew: float('it_cena_new'),
    promotNew: varchar('promot_new', { length: 20 }),
    catNo: varchar('cat_no', { length: 255 }),
    ime: varchar({ length: 511 }),
    miarka: varchar({ length: 31 }),
    imeLat: varchar('ime_lat', { length: 255 }),
    potrId: varchar('potr_id', { length: 31 }),
    potrIme: varchar('potr_ime', { length: 511 }),
    q0011Sklad: int('q0011_sklad').default(0).notNull(),
    q03Bucuresti: int('q03_bucuresti').default(0).notNull(),
    q12Burgas: int('q12_burgas').default(0).notNull(),
    q14Burgascentar: int('q14_burgascentar').default(0).notNull(),
    q15Burgashobby: int('q15_burgashobby').default(0).notNull(),
    q22Sofia: int('q22_sofia').default(0).notNull(),
    q23Sofiandk: int('q23_sofiandk').default(0).notNull(),
    q24Szagora: int('q24_szagora').default(0).notNull(),
    q26Varna: int('q26_varna').default(0).notNull(),
    q28Ruse: int('q28_ruse').default(0).notNull(),
    q31Vtarnovo: int('q31_vtarnovo').default(0).notNull(),
    q32Shumen: int('q32_shumen').default(0).notNull(),
    q34Yambol: int('q34_yambol').default(0).notNull(),
    q36Haskovo: int('q36_haskovo').default(0).notNull(),
    q38Goriahovica: int('q38_goriahovica').default(0).notNull(),
    q41Sliven: int('q41_sliven').default(0).notNull(),
    q43Plovdiv: int('q43_plovdiv').default(0).notNull(),
    q51Burgaskiki: int('q51_burgaskiki').default(0).notNull(),
    q100Slujeben: int('q100_slujeben').default(0).notNull(),
    prom: int().default(1).notNull(),
    zelen: int().default(1).notNull(),
    ip: varchar({ length: 15 }),
  },
  table => [primaryKey({ columns: [table.itemId], name: 'itemiztrit_item_id' })],
);

export const klienti = mysqlTable(
  'klienti',
  {
    klientiId: int('klienti_id').autoincrement().notNull(),
    emailReg: varchar('email_reg', { length: 127 }),
    parola: varchar({ length: 127 }),
    email: varchar({ length: 127 }),
    imeFamilia: varchar('ime_familia', { length: 255 }),
    imeFamiliaAdr: varchar('ime_familia_adr', { length: 255 }),
    darjava: varchar({ length: 127 }),
    region: varchar({ length: 127 }),
    oblast: varchar({ length: 127 }),
    obshtina: varchar({ length: 127 }),
    gradSelo: varchar('grad_selo', { length: 127 }),
    postKod: varchar('post_kod', { length: 31 }),
    adres: varchar({ length: 511 }),
    telefon: varchar({ length: 63 }),
    brDopAdresi: int('br_dop_adresi').default(0).notNull(),
    dataReg: varchar('data_reg', { length: 63 }),
    dataPromiana: timestamp('data_promiana', { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
    fFirma: varchar('f_firma', { length: 255 }),
    fEik: varchar('f_eik', { length: 63 }),
    fDds: varchar('f_dds', { length: 63 }),
    fDarjava: varchar('f_darjava', { length: 127 }),
    fOblast: varchar('f_oblast', { length: 127 }),
    fObshtina: varchar('f_obshtina', { length: 127 }),
    fGradSelo: varchar('f_grad_selo', { length: 127 }),
    fPostKod: varchar('f_post_kod', { length: 31 }),
    fAdres: varchar('f_adres', { length: 511 }),
    fTelefon: varchar('f_telefon', { length: 63 }),
    fMol: varchar('f_mol', { length: 255 }),
    fPoluchatel: varchar('f_poluchatel', { length: 255 }),
    brDopFirmi: int('br_dop_firmi').default(0).notNull(),
    otstapka: int().default(0).notNull(),
    otstapka2: int().default(0).notNull(),
    otstapka3: int().default(0).notNull(),
    grupaOtstapki: int('grupa_otstapki').default(0).notNull(),
    zakluchen: int().default(1).notNull(),
    status: int().default(1).notNull(),
    emailOtpisani: int('email_otpisani').default(1).notNull(),
    emailOtpisaniData: varchar('email_otpisani_data', { length: 63 }),
    emailGreshen: int('email_greshen').default(1).notNull(),
    reklama: int().default(1).notNull(),
    grupa: varchar({ length: 127 }),
    kategorizacia: varchar({ length: 127 }),
    tip: varchar({ length: 127 }),
    komentar: text(),
    zabelejki: text(),
    microkod: varchar({ length: 63 }),
    microddsbanka: int().default(0).notNull(),
    broiPorachki: int('broi_porachki').default(0).notNull(),
    suma: float().notNull(),
    pordataLast: varchar('pordata_last', { length: 63 }),
    porizpLastStatus: varchar('porizp_last_status', { length: 127 }),
    telefon2: varchar({ length: 63 }),
    email2: varchar({ length: 511 }),
    www: varchar({ length: 255 }),
    ip: varchar({ length: 31 }),
    zapomniMe: int('zapomni_me').default(1).notNull(),
    izbranAdres: int('izbran_adres').default(0).notNull(),
    izbranaFirma: int('izbrana_firma').default(0).notNull(),
    idSvarzaniKlienti: varchar('id_svarzani_klienti', { length: 127 }),
    ivoDublNo: varchar('ivo_dubl_no', { length: 63 }),
    ivoDubl: varchar('ivo_dubl', { length: 63 }),
    ivoDubl2: varchar('ivo_dubl2', { length: 127 }),
    dublMicro: varchar('dubl_micro', { length: 127 }),
    ivoSort1: varchar('ivo_sort1', { length: 127 }),
    ivoSort2: varchar('ivo_sort2', { length: 127 }),
    ivoSort3: varchar('ivo_sort3', { length: 127 }),
    ivoSort4: varchar('ivo_sort4', { length: 127 }),
    ivoComent: varchar('ivo_coment', { length: 127 }),
    ivoComent2: varchar('ivo_coment2', { length: 127 }),
    broiLogvania: int('broi_logvania').default(0).notNull(),
    dataPoslLogvane: varchar('data_posl_logvane', { length: 15 }),
    oldGrad: varchar('old_grad', { length: 255 }),
    oldNik: varchar('old_nik', { length: 63 }),
    oldVapros: varchar('old_vapros', { length: 127 }),
    oldOtgovor: varchar('old_otgovor', { length: 127 }),
    oldIme: varchar('old_ime', { length: 127 }),
    oldPrezime: varchar('old_prezime', { length: 127 }),
    oldFamilia: varchar('old_familia', { length: 127 }),
    oldPol: varchar('old_pol', { length: 15 }),
    oldRDataD: int('old_r_data_d').default(0).notNull(),
    oldRDataM: varchar('old_r_data_m', { length: 31 }),
    oldRDataG: int('old_r_data_g').default(0).notNull(),
    fid: varchar({ length: 31 }),
    regot: varchar({ length: 1 }),
    imeFirst: varchar('ime_first', { length: 127 }),
    imeMiddle: varchar('ime_middle', { length: 127 }),
    imeLast: varchar('ime_last', { length: 127 }),
    otcite: varchar({ length: 15 }),
    rojdennaData: varchar('rojdenna_data', { length: 63 }),
  },
  table => [
    primaryKey({ columns: [table.klientiId], name: 'klienti_klienti_id' }),
    unique('email_reg').on(table.emailReg),
  ],
);

export const klientiDopAdresi = mysqlTable(
  'klienti_dop_adresi',
  {
    klientiDopAdresiId: int('klienti_dop_adresi_id').autoincrement().notNull(),
    klientiId: int('klienti_id').notNull(),
    imeFamilia: varchar('ime_familia', { length: 255 }),
    darjava: varchar({ length: 127 }),
    region: varchar({ length: 127 }),
    oblast: varchar({ length: 127 }),
    obshtina: varchar({ length: 127 }),
    gradSelo: varchar('grad_selo', { length: 127 }),
    postKod: varchar('post_kod', { length: 31 }),
    adres: varchar({ length: 511 }),
    telefon: varchar({ length: 63 }),
  },
  table => [primaryKey({ columns: [table.klientiDopAdresiId], name: 'klienti_dop_adresi_klienti_dop_adresi_id' })],
);

export const klientiDopFirmi = mysqlTable(
  'klienti_dop_firmi',
  {
    klientiDopFirmiId: int('klienti_dop_firmi_id').autoincrement().notNull(),
    klientiId: int('klienti_id').notNull(),
    fFirma: varchar('f_firma', { length: 255 }),
    fEik: varchar('f_eik', { length: 63 }),
    fDds: varchar('f_dds', { length: 63 }),
    fDarjava: varchar('f_darjava', { length: 127 }),
    fOblast: varchar('f_oblast', { length: 127 }),
    fObshtina: varchar('f_obshtina', { length: 127 }),
    fGradSelo: varchar('f_grad_selo', { length: 127 }),
    fPostKod: varchar('f_post_kod', { length: 31 }),
    fAdres: varchar('f_adres', { length: 511 }),
    fTelefon: varchar('f_telefon', { length: 63 }),
    fMol: varchar('f_mol', { length: 255 }),
    fPoluchatel: varchar('f_poluchatel', { length: 255 }),
  },
  table => [primaryKey({ columns: [table.klientiDopFirmiId], name: 'klienti_dop_firmi_klienti_dop_firmi_id' })],
);

export const klientiIp = mysqlTable(
  'klienti_ip',
  {
    id: int().autoincrement().notNull(),
    email: varchar({ length: 255 }),
    ip: varchar({ length: 15 }),
    br: int().default(0).notNull(),
    mango: varchar({ length: 63 }),
  },
  table => [primaryKey({ columns: [table.id], name: 'klienti_ip_id' })],
);

export const klientiLog = mysqlTable(
  'klienti_log',
  {
    id: int().autoincrement().notNull(),
    idKlient: int('id_klient').notNull(),
    email: varchar({ length: 255 }),
    ipLastLog: varchar('ip_last_log', { length: 15 }),
    dataLog: varchar('data_log', { length: 15 }),
    fid: varchar({ length: 255 }),
    komentar1: text(),
    komentar2: text(),
    fbId: varchar('fb_id', { length: 255 }),
    fbGoogleRegistered: int('fb_google_registered').default(0).notNull(),
    fbLastDataLogged: varchar('fb_last_data_logged', { length: 15 }),
    googleLastDataLogged: varchar('google_last_data_logged', { length: 15 }),
    imeFirst: varchar('ime_first', { length: 255 }),
    logNeLog: int('log_ne_log').default(0).notNull(),
    otKade: varchar('ot_kade', { length: 31 }),
  },
  table => [primaryKey({ columns: [table.id], name: 'klienti_log_id' })],
);

export const poliaci = mysqlTable(
  'poliaci',
  {
    poliaciId: int('poliaci_id').autoincrement().notNull(),
    potrebid: int().default(0).notNull(),
    ime: varchar({ length: 255 }),
    email: varchar({ length: 255 }),
    poliaciid: varchar({ length: 63 }),
    message: text(),
    success: int().default(1).notNull(),
    external: varchar({ length: 255 }),
    datata: varchar({ length: 15 }),
    ipto: varchar({ length: 15 }),
    otkade: varchar({ length: 15 }),
    otskript: varchar({ length: 31 }),
  },
  table => [primaryKey({ columns: [table.poliaciId], name: 'poliaci_poliaci_id' })],
);

export const poliaci1 = mysqlTable(
  'poliaci1',
  {
    poliaciId: int('poliaci_id').autoincrement().notNull(),
    potrebid: int().default(0).notNull(),
    ime: varchar({ length: 255 }),
    email: varchar({ length: 255 }),
    poliaciid: varchar({ length: 63 }),
    message: text(),
    success: int().default(1).notNull(),
    external: varchar({ length: 255 }),
    datata: varchar({ length: 15 }),
    ipto: varchar({ length: 15 }),
    otkade: varchar({ length: 15 }),
    otskript: varchar({ length: 31 }),
  },
  table => [primaryKey({ columns: [table.poliaciId], name: 'poliaci1_poliaci_id' })],
);

export const poliaciOldDo20211216 = mysqlTable(
  'poliaci_old_do_20211216',
  {
    poliaciId: int('poliaci_id').autoincrement().notNull(),
    potrebid: int().default(0).notNull(),
    ime: varchar({ length: 255 }),
    email: varchar({ length: 255 }),
    poliaciid: varchar({ length: 63 }),
    message: text(),
    success: int().default(1).notNull(),
    external: varchar({ length: 255 }),
    datata: varchar({ length: 15 }),
    ipto: varchar({ length: 15 }),
    otkade: varchar({ length: 15 }),
    otskript: varchar({ length: 31 }),
  },
  table => [primaryKey({ columns: [table.poliaciId], name: 'poliaci_old_do_20211216_poliaci_id' })],
);

export const porachki = mysqlTable(
  'porachki',
  {
    porachkiId: int('porachki_id').autoincrement().notNull(),
    potrebId: int('potreb_id').default(0).notNull(),
    porach: int().default(1).notNull(),
    pordata: varchar({ length: 31 }),
    pordost: int().default(0).notNull(),
    porizp: int().default(0).notNull(),
    porizpIme: varchar('porizp_ime', { length: 255 }).default('Нов').notNull(),
    porizpdat: varchar({ length: 31 }),
    broiDni: int('broi_dni').default(0).notNull(),
    porgr: int().default(0).notNull(),
    porcomtr: text(),
    porcomadm: text(),
    porcor: varchar({ length: 255 }),
    shtane: varchar({ length: 255 }),
    tovaritelnica: varchar({ length: 127 }),
    kodMicro: varchar('kod_micro', { length: 51 }),
    izpalnId: int('izpaln_id').default(0).notNull(),
    izpalnIme: varchar('izpaln_ime', { length: 255 }),
    infoMy: int('info_my').default(1).notNull(),
    doKade: int('do_kade').default(1).notNull(),
    faktura: int().default(1).notNull(),
    izbranAdr: int('izbran_adr').default(0).notNull(),
    izpaln1Id: int('izpaln1_id').default(0).notNull(),
    izpaln1Ime: varchar('izpaln1_ime', { length: 255 }),
    magazId: int('magaz_id').default(0).notNull(),
    magazIme: varchar('magaz_ime', { length: 255 }),
    magaz1Id: int('magaz1_id').default(0).notNull(),
    magaz1Ime: varchar('magaz1_ime', { length: 255 }),
    poluchsumi: int().default(0).notNull(),
    poluchsuma: float().notNull(),
    poluchsumd: varchar({ length: 31 }),
    broiPera: int('broi_pera').default(0).notNull(),
    porachSuma: float('porach_suma').notNull(),
    email: varchar({ length: 127 }),
    imeFamilia: varchar('ime_familia', { length: 255 }),
    imeFamiliaAdr: varchar('ime_familia_adr', { length: 255 }),
    darjava: varchar({ length: 127 }),
    region: varchar({ length: 127 }),
    oblast: varchar({ length: 127 }),
    obshtina: varchar({ length: 127 }),
    gradSelo: varchar('grad_selo', { length: 127 }),
    postKod: varchar('post_kod', { length: 63 }),
    adres: varchar({ length: 511 }),
    telefon: varchar({ length: 63 }),
    fFirma: varchar('f_firma', { length: 255 }),
    fEik: varchar('f_eik', { length: 63 }),
    fDds: varchar('f_dds', { length: 63 }),
    fDarjava: varchar('f_darjava', { length: 127 }),
    fOblast: varchar('f_oblast', { length: 127 }),
    fObshtina: varchar('f_obshtina', { length: 127 }),
    fGradSelo: varchar('f_grad_selo', { length: 127 }),
    fPostKod: varchar('f_post_kod', { length: 63 }),
    fAdres: varchar('f_adres', { length: 511 }),
    fTelefon: varchar('f_telefon', { length: 63 }),
    fMol: varchar('f_mol', { length: 255 }),
    fPoluchatel: varchar('f_poluchatel', { length: 255 }),
    izbranAdres: int('izbran_adres').default(0).notNull(),
    izbranaFirma: int('izbrana_firma').default(0).notNull(),
    brkomen: int().default(0).notNull(),
    cendost: float(),
    klmicrokod: varchar({ length: 63 }),
    otSite: varchar('ot_site', { length: 31 }),
    ip: varchar({ length: 15 }),
    valuta: varchar({ length: 15 }),
    kurs: float().notNull(),
    kurr: float().default(1).notNull(),
    tipdds: int().default(1).notNull(),
    cendostIzchislena: float('cendost_izchislena').notNull(),
    cendostEmartPlashta: float('cendost_emart_plashta').notNull(),
    cendostKurierRealna: float('cendost_kurier_realna').notNull(),
    cendostKurierEmart: float('cendost_kurier_emart').notNull(),
  },
  table => [primaryKey({ columns: [table.porachkiId], name: 'porachki_porachki_id' })],
);

export const porachkiMsg = mysqlTable(
  'porachki_msg',
  {
    porachkiMsgId: int('porachki_msg_id').autoincrement().notNull(),
    porachkiId: int('porachki_id'),
    msgText: text('msg_text'),
    msgEmail: int('msg_email').default(1).notNull(),
    msgData: varchar('msg_data', { length: 20 }),
    msgKol: int('msg_kol').default(1).notNull(),
  },
  table => [
    index('porachki_id').on(table.porachkiId),
    primaryKey({ columns: [table.porachkiMsgId], name: 'porachki_msg_porachki_msg_id' }),
  ],
);

export const porachkimsgiztrit = mysqlTable(
  'porachkimsgiztrit',
  {
    porachkiMsgId: int('porachki_msg_id').autoincrement().notNull(),
    porachkiId: int('porachki_id'),
    msgText: text('msg_text'),
    msgEmail: int('msg_email').default(1).notNull(),
    msgData: varchar('msg_data', { length: 20 }),
  },
  table => [primaryKey({ columns: [table.porachkiMsgId], name: 'porachkimsgiztrit_porachki_msg_id' })],
);

export const porachkiztriti = mysqlTable(
  'porachkiztriti',
  {
    porachkiId: int('porachki_id').autoincrement().notNull(),
    potrebId: int('potreb_id').default(0).notNull(),
    porach: int().default(1).notNull(),
    pordata: varchar({ length: 31 }),
    pordost: int().default(0).notNull(),
    porizp: int().default(0).notNull(),
    porizpIme: varchar('porizp_ime', { length: 255 }),
    porizpdat: varchar({ length: 31 }),
    broiDni: int('broi_dni').default(0).notNull(),
    porgr: int().default(0).notNull(),
    porcomtr: text(),
    porcomadm: text(),
    porcor: varchar({ length: 63 }),
    shtane: varchar({ length: 255 }),
    tovaritelnica: varchar({ length: 127 }),
    kodMicro: varchar('kod_micro', { length: 51 }),
    izpalnId: int('izpaln_id').default(0).notNull(),
    izpalnIme: varchar('izpaln_ime', { length: 255 }),
    infoMy: int('info_my').default(1).notNull(),
    doKade: int('do_kade').default(1).notNull(),
    faktura: int().default(1).notNull(),
    izbranAdr: int('izbran_adr').default(0).notNull(),
    izpaln1Id: int('izpaln1_id').default(0).notNull(),
    izpaln1Ime: varchar('izpaln1_ime', { length: 255 }),
    magazId: int('magaz_id').default(0).notNull(),
    magazIme: varchar('magaz_ime', { length: 255 }),
    magaz1Id: int('magaz1_id').default(0).notNull(),
    magaz1Ime: varchar('magaz1_ime', { length: 255 }),
    poluchsumi: int().default(0).notNull(),
    poluchsuma: float().notNull(),
    poluchsumd: varchar({ length: 31 }),
    broiPera: int('broi_pera').default(0).notNull(),
    porachSuma: float('porach_suma').notNull(),
    email: varchar({ length: 127 }),
    imeFamilia: varchar('ime_familia', { length: 255 }),
    imeFamiliaAdr: varchar('ime_familia_adr', { length: 255 }),
    darjava: varchar({ length: 127 }),
    region: varchar({ length: 127 }),
    oblast: varchar({ length: 127 }),
    obshtina: varchar({ length: 127 }),
    gradSelo: varchar('grad_selo', { length: 127 }),
    postKod: varchar('post_kod', { length: 63 }),
    adres: varchar({ length: 511 }),
    telefon: varchar({ length: 63 }),
    fFirma: varchar('f_firma', { length: 255 }),
    fEik: varchar('f_eik', { length: 63 }),
    fDds: varchar('f_dds', { length: 63 }),
    fDarjava: varchar('f_darjava', { length: 127 }),
    fOblast: varchar('f_oblast', { length: 127 }),
    fObshtina: varchar('f_obshtina', { length: 127 }),
    fGradSelo: varchar('f_grad_selo', { length: 127 }),
    fPostKod: varchar('f_post_kod', { length: 63 }),
    fAdres: varchar('f_adres', { length: 511 }),
    fTelefon: varchar('f_telefon', { length: 63 }),
    fMol: varchar('f_mol', { length: 255 }),
    fPoluchatel: varchar('f_poluchatel', { length: 255 }),
    izbranAdres: int('izbran_adres').default(0).notNull(),
    izbranaFirma: int('izbrana_firma').default(0).notNull(),
    brkomen: int().default(0).notNull(),
    cendost: float(),
    klmicrokod: varchar({ length: 63 }),
    otSite: varchar('ot_site', { length: 31 }),
    ip: varchar({ length: 15 }),
    valuta: varchar({ length: 15 }),
    dataiztr: varchar({ length: 15 }),
    koiiztrid: int().default(0).notNull(),
  },
  table => [primaryKey({ columns: [table.porachkiId], name: 'porachkiztriti_porachki_id' })],
);

export const promociiQ = mysqlTable(
  'promocii_q',
  {
    catalogId: int('catalog_id').autoincrement().notNull(),
    catNo: varchar('cat_no', { length: 255 }),
    ime: varchar({ length: 511 }),
    qTotalNalichni: int('q_total_nalichni').default(0).notNull(),
    qTotalPorachani: int('q_total_porachani').default(0).notNull(),
    qCountPorachani: int('q_count_porachani').default(0).notNull(),
    qTotalNalichniStart: int('q_total_nalichni_start').default(1).notNull(),
    aktivnaNeaktivna: int('aktivna_neaktivna').notNull(),
    data: varchar({ length: 64 }),
    koment1: text('koment_1'),
    koment2: text('koment_2'),
    cena: float({ precision: 5, scale: 2 }).notNull(),
    grOtst: float('gr_otst').notNull(),
    br1: int('br_1').default(0).notNull(),
    cena1: float('cena_1', { precision: 5, scale: 2 }).notNull(),
    br2: int('br_2').default(0).notNull(),
    cena2: float('cena_2', { precision: 5, scale: 2 }).notNull(),
    prioritetMicro: varchar('prioritet_micro', { length: 63 }),
    tipStokata: varchar('tip_stokata', { length: 255 }),
    q0011Sklad: int('q0011_sklad').default(0).notNull(),
    q12Burgas: int('q12_burgas').default(0).notNull(),
    q14Burgascentar: int('q14_burgascentar').default(0).notNull(),
    q15Burgashobby: int('q15_burgashobby').default(0).notNull(),
    q22Sofia: int('q22_sofia').default(0).notNull(),
    q23Sofiandk: int('q23_sofiandk').default(0).notNull(),
    q24Szagora: int('q24_szagora').default(0).notNull(),
    q26Varna: int('q26_varna').default(0).notNull(),
    q28Ruse: int('q28_ruse').default(0).notNull(),
    q31Vtarnovo: int('q31_vtarnovo').default(0).notNull(),
    q32Shumen: int('q32_shumen').default(0).notNull(),
    q34Yambol: int('q34_yambol').default(0).notNull(),
    q36Haskovo: int('q36_haskovo').default(0).notNull(),
    q43Plovdiv: int('q43_plovdiv').default(0).notNull(),
    qTotal: int('q_total').default(0).notNull(),
    qCountNalichniVMagazini: int('q_count_nalichni_v_magazini').default(0).notNull(),
    dostCena: float('dost_cena', { precision: 5, scale: 2 }).notNull(),
    pCengr2: float('p_cengr_2').notNull(),
    pCengr3: float('p_cengr_3').notNull(),
    koment3: text('koment_3'),
    koment4: text('koment_4'),
    vidimost: int().default(0).notNull(),
    pActi: int('p_acti').default(0).notNull(),
    bezKolichka: int('bez_kolichka').default(0).notNull(),
    novaStokaAktiv: int('nova_stoka_aktiv').default(0).notNull(),
    nalichnost: int().default(0).notNull(),
  },
  table => [
    primaryKey({ columns: [table.catalogId], name: 'promocii_q_catalog_id' }),
    unique('cat_no').on(table.catNo),
  ],
);

export const rating = mysqlTable(
  'rating',
  {
    ratingId: int('rating_id').autoincrement().notNull(),
    kod: varchar({ length: 255 }),
    ocenka: int().default(5).notNull(),
    sesiaId: int('sesia_id').default(0).notNull(),
    klientId: int('klient_id').default(0).notNull(),
    otsite: varchar({ length: 7 }).default('bg').notNull(),
  },
  table => [
    index('kod').on(table.kod),
    index('sesia_id').on(table.sesiaId),
    primaryKey({ columns: [table.ratingId], name: 'rating_rating_id' }),
  ],
);

export const ratingPrazna = mysqlTable(
  'rating_prazna',
  {
    ratingId: int('rating_id').autoincrement().notNull(),
    kod: varchar({ length: 255 }),
    ocenka: int().default(5).notNull(),
    sesiaId: int('sesia_id').default(0).notNull(),
    klientId: int('klient_id').default(0).notNull(),
    otsite: varchar({ length: 7 }).default('').notNull(),
  },
  table => [
    index('kod').on(table.kod),
    index('sesia_id').on(table.sesiaId),
    primaryKey({ columns: [table.ratingId], name: 'rating_prazna_rating_id' }),
  ],
);

export const smizp = mysqlTable(
  'smizp',
  {
    smizpId: int('smizp_id').autoincrement().notNull(),
    porid: int().default(0).notNull(),
    magid: int().default(0).notNull(),
    magime: varchar({ length: 255 }),
    izpid: int().default(0).notNull(),
    izpime: varchar({ length: 255 }),
    sumid: int().default(0).notNull(),
    sumime: varchar({ length: 255 }),
    suma: float().notNull(),
    koga: varchar({ length: 15 }),
    koiid: int().default(0).notNull(),
    koiime: varchar({ length: 255 }),
  },
  table => [
    index('izpid').on(table.izpid),
    index('koga').on(table.koga),
    index('magid').on(table.magid),
    index('porid').on(table.porid),
    index('sumid').on(table.sumid),
    primaryKey({ columns: [table.smizpId], name: 'smizp_smizp_id' }),
  ],
);

export const smstat = mysqlTable(
  'smstat',
  {
    smstatId: int('smstat_id').autoincrement().notNull(),
    porid: int().default(0).notNull(),
    statid: int().default(0).notNull(),
    statime: varchar({ length: 255 }),
    koga: varchar({ length: 15 }),
    koiid: int().default(0).notNull(),
    koiime: varchar({ length: 255 }),
  },
  table => [
    index('koga').on(table.koga),
    index('porid').on(table.porid),
    primaryKey({ columns: [table.smstatId], name: 'smstat_smstat_id' }),
  ],
);

export const snimki = mysqlTable(
  'snimki',
  {
    snimkiId: int('snimki_id').autoincrement().notNull(),
    catno: varchar({ length: 255 }).default('').notNull(),
    ime: varchar({ length: 255 }).default('').notNull(),
    direk: varchar({ length: 255 }).default('').notNull(),
    shirochina: int().default(0).notNull(),
    visochina: int().default(0).notNull(),
    cviat: varchar({ length: 128 }).default('').notNull(),
    nomer: int().default(0).notNull(),
    tip: int().default(0).notNull(),
  },
  table => [index('catno').on(table.catno), primaryKey({ columns: [table.snimkiId], name: 'snimki_snimki_id' })],
);

export const tuvar = mysqlTable(
  'tuvar',
  {
    tuvarId: int('tuvar_id').autoincrement().notNull(),
    porid: int().default(0).notNull(),
    tovari: varchar({ length: 255 }),
    cd1: float().notNull(),
    cd2: float().notNull(),
    koga: varchar({ length: 15 }),
    koiid: int().default(0).notNull(),
    koiime: varchar({ length: 255 }),
  },
  table => [primaryKey({ columns: [table.tuvarId], name: 'tuvar_tuvar_id' })],
);

export const txtIp = mysqlTable(
  'txt_ip',
  {
    id: int().autoincrement().notNull(),
    tip: int().default(0).notNull(),
    ip: varchar({ length: 31 }).notNull(),
    opis: text().notNull(),
  },
  table => [primaryKey({ columns: [table.id], name: 'txt_ip_id' })],
);
